language: node_js
node_js:
  - "6"

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --ignore-engines --no-lockfile --non-interactive

script:
  - yarn lint:js
  - yarn test

before_deploy:
  - yarn global add auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: GJexXCwAwkiezqiivJLdCDcwHyNOkyWGhaIC9wEovlrmn6UZlNL1lZvkTHBMaxFRtTa5ZmwLWHCLPiNIbpqFb1JdSpmAq+7P/qjSMMm6JO8hlA8Yn57TP4rZKG++xKRjZe7f13K5yqrJWFtWyHiBppU047GAP8gBsBlcjUVzAGM=
  on:
    tags: true
    repo: ember-cli/ember-cli-eslint
